import { INK, PARCHMENT, PARCHMENT_DARK, SEA, SEA_DEEP, GOLD } from "./game/constants.js";

export const styles = {
  homeWrap: {
    minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center",
    background: `radial-gradient(circle at 50% 20%, ${SEA} 0%, ${SEA_DEEP} 70%)`,
    fontFamily: "Georgia, 'Times New Roman', serif", padding: 20,
  },
  homeCard: {
    background: PARCHMENT, borderRadius: 10, padding: "32px 28px", width: 340, maxWidth: "100%",
    boxShadow: "0 20px 60px rgba(0,0,0,0.45)", border: `2px solid ${GOLD}`, textAlign: "center",
  },
  compass: { fontSize: 40, marginBottom: 4 },
  title: { fontSize: 34, letterSpacing: 4, color: INK, margin: "0 0 4px", fontWeight: 900 },
  subtitle: { color: "#5a4a35", fontSize: 13, marginBottom: 18 },
  input: {
    width: "100%", padding: "10px 12px", marginBottom: 10, borderRadius: 6, border: `1.5px solid ${GOLD}`,
    background: "#fbf6e8", fontSize: 15, boxSizing: "border-box", color: INK,
  },
  primaryBtn: {
    width: "100%", padding: "11px 14px", borderRadius: 6, border: "none", background: SEA, color: PARCHMENT,
    fontSize: 14, fontWeight: 700, cursor: "pointer", marginBottom: 8, display: "flex", alignItems: "center", justifyContent: "center",
  },
  secondaryBtn: {
    width: "100%", padding: "10px 14px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: "transparent",
    color: SEA, fontSize: 13, fontWeight: 700, cursor: "pointer", marginBottom: 8,
  },
  dividerRow: { display: "flex", alignItems: "center", gap: 8, margin: "8px 0" },
  hr: { flex: 1, height: 1, background: GOLD, opacity: 0.5 },
  dividerText: { fontSize: 11, color: "#5a4a35" },
  codeRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginBottom: 6 },
  codeText: { fontSize: 28, letterSpacing: 6, fontWeight: 900, color: SEA },
  iconBtn: { border: "none", background: PARCHMENT_DARK, borderRadius: 6, padding: 6, cursor: "pointer" },
  playerList: { textAlign: "left", margin: "14px 0" },
  playerRow: { display: "flex", alignItems: "center", gap: 8, padding: "6px 0", color: INK, fontSize: 14 },

  gameWrap: { minHeight: "100vh", background: SEA_DEEP, fontFamily: "Georgia, serif", color: PARCHMENT },
  topBar: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 16px", background: INK, flexWrap: "wrap", gap: 6 },
  topBarTitle: { fontWeight: 900, letterSpacing: 2, fontSize: 16 },
  topBarCode: { fontSize: 11, opacity: 0.7, marginLeft: 6 },
  turnBanner: { fontSize: 13, background: GOLD, color: INK, padding: "4px 12px", borderRadius: 20, fontWeight: 700 },
  mainArea: { display: "flex", flexWrap: "wrap", gap: 12, padding: 12 },
  boardPanel: { flex: "2 1 420px", minWidth: 300, background: SEA, borderRadius: 10, border: `2px solid ${GOLD}`, overflow: "hidden" },
  svg: { width: "100%", height: "auto", display: "block", minHeight: 380 },
  sidePanel: { flex: "1 1 300px", minWidth: 280, display: "flex", flexDirection: "column", gap: 10 },
  card: { background: PARCHMENT, color: INK, borderRadius: 8, padding: 12, border: `1.5px solid ${GOLD}` },
  cardTitle: { fontWeight: 800, fontSize: 13, marginBottom: 8, display: "flex", alignItems: "center", textTransform: "uppercase", letterSpacing: 1 },
  resRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  resChip: { color: "#fff", borderRadius: 6, padding: "4px 8px", fontSize: 11, display: "flex", flexDirection: "column", alignItems: "center", minWidth: 52, border: "none", fontFamily: "inherit" },
  devRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 },
  devChip: { background: PARCHMENT_DARK, borderRadius: 6, padding: "4px 8px", fontSize: 11, display: "flex", alignItems: "center", gap: 6 },
  miniBtn: { border: "none", background: SEA, color: PARCHMENT, borderRadius: 4, padding: "2px 6px", fontSize: 10, cursor: "pointer" },
  actionGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 8 },
  toggleBtn: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", padding: "8px 6px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: "transparent", color: SEA, fontSize: 11, fontWeight: 700, cursor: "pointer" },
  toggleBtnActive: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", padding: "8px 6px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: SEA, color: PARCHMENT, fontSize: 11, fontWeight: 700, cursor: "pointer" },
  hint: { fontSize: 12, color: "#5a4a35", marginBottom: 6 },
  playerCard: { display: "flex", alignItems: "center", gap: 8, padding: "6px 4px", borderLeft: "4px solid", marginBottom: 4, borderRadius: 4 },
  playerDot: { width: 10, height: 10, borderRadius: "50%" },
  playerCardBody: { flex: 1 },
  playerCardName: { fontWeight: 700, fontSize: 13 },
  playerCardMeta: { fontSize: 10.5, color: "#5a4a35" },
  discardRow: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 12, marginBottom: 4 },
  stepper: { display: "flex", alignItems: "center", gap: 6 },
  tradeRow: { display: "flex", gap: 8, marginBottom: 8 },
  select: { width: "100%", padding: 6, borderRadius: 6, border: `1.5px solid ${GOLD}`, background: "#fbf6e8", fontSize: 12 },
  logBox: { maxHeight: 160, overflowY: "auto", fontSize: 11.5, lineHeight: 1.5 },
  logLine: { borderBottom: "1px solid rgba(0,0,0,0.08)", padding: "3px 0" },
};
