import { INK, PARCHMENT, PARCHMENT_DARK, SEA, SEA_DEEP, GOLD } from "./game/constants.js";

export const styles = {
  homeWrap: {
    minHeight: "100dvh", display: "flex", alignItems: "center", justifyContent: "center",
    background: `radial-gradient(circle at 50% 20%, ${SEA} 0%, ${SEA_DEEP} 70%)`,
    fontFamily: "Georgia, 'Times New Roman', serif", padding: 20,
    paddingTop: "max(20px, env(safe-area-inset-top))",
    paddingBottom: "max(20px, env(safe-area-inset-bottom))",
  },
  homeCard: {
    background: PARCHMENT, borderRadius: 10, padding: "32px 28px", width: 340, maxWidth: "100%",
    boxShadow: "0 20px 60px rgba(0,0,0,0.45)", border: `2px solid ${GOLD}`, textAlign: "center",
  },
  compass: { fontSize: 40, marginBottom: 4 },
  title: { fontSize: "clamp(28px, 8vw, 34px)", letterSpacing: 4, color: INK, margin: "0 0 4px", fontWeight: 900 },
  subtitle: { color: "#5a4a35", fontSize: 14, marginBottom: 18 },
  input: {
    width: "100%", padding: "12px 12px", marginBottom: 10, borderRadius: 6, border: `1.5px solid ${GOLD}`,
    background: "#fbf6e8", fontSize: 16, boxSizing: "border-box", color: INK,
  },
  primaryBtn: {
    width: "100%", padding: "13px 14px", borderRadius: 6, border: "none", background: SEA, color: PARCHMENT,
    fontSize: 15, fontWeight: 700, cursor: "pointer", marginBottom: 8, display: "flex", alignItems: "center",
    justifyContent: "center", minHeight: 44,
  },
  secondaryBtn: {
    width: "100%", padding: "12px 14px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: "transparent",
    color: SEA, fontSize: 14, fontWeight: 700, cursor: "pointer", marginBottom: 8, minHeight: 44,
  },
  dividerRow: { display: "flex", alignItems: "center", gap: 8, margin: "8px 0" },
  hr: { flex: 1, height: 1, background: GOLD, opacity: 0.5 },
  dividerText: { fontSize: 12, color: "#5a4a35" },
  codeRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 8, marginBottom: 6 },
  codeText: { fontSize: "clamp(24px, 7vw, 28px)", letterSpacing: 6, fontWeight: 900, color: SEA },
  iconBtn: { border: "none", background: PARCHMENT_DARK, borderRadius: 6, padding: 8, cursor: "pointer", minHeight: 36, minWidth: 36 },
  playerList: { textAlign: "left", margin: "14px 0" },
  playerRow: { display: "flex", alignItems: "center", gap: 8, padding: "7px 0", color: INK, fontSize: 15 },

  gameWrap: {
    minHeight: "100dvh",
    background: `radial-gradient(circle at 50% 0%, ${SEA} 0%, ${SEA_DEEP} 65%)`,
    fontFamily: "Georgia, serif", color: PARCHMENT,
  },
  topBar: {
    display: "flex", justifyContent: "space-between", alignItems: "center",
    padding: "12px 16px", paddingTop: "max(12px, env(safe-area-inset-top))",
    background: INK, flexWrap: "wrap", gap: 8, boxShadow: "0 2px 8px rgba(0,0,0,0.4)",
    position: "sticky", top: 0, zIndex: 10,
  },
  topBarTitle: { fontWeight: 900, letterSpacing: 2, fontSize: "clamp(15px, 4vw, 17px)" },
  topBarCode: { fontSize: 12, opacity: 0.75, marginLeft: 6 },
  turnBanner: { fontSize: 13, background: GOLD, color: INK, padding: "5px 13px", borderRadius: 20, fontWeight: 700, boxShadow: "0 2px 4px rgba(0,0,0,0.3)" },
  mainArea: { display: "flex", flexWrap: "wrap", gap: 12, padding: "12px", paddingBottom: "max(12px, env(safe-area-inset-bottom))" },
  boardPanel: { flex: "2 1 420px", minWidth: 300, background: SEA, borderRadius: 12, border: `3px solid ${GOLD}`, overflow: "hidden", boxShadow: "0 10px 30px rgba(0,0,0,0.5), inset 0 0 40px rgba(0,0,0,0.25)" },
  svg: { width: "100%", height: "auto", display: "block", minHeight: 320 },
  sidePanel: { flex: "1 1 300px", minWidth: 280, display: "flex", flexDirection: "column", gap: 10 },
  card: { background: PARCHMENT, color: INK, borderRadius: 10, padding: 14, border: `1.5px solid ${GOLD}`, boxShadow: "0 4px 12px rgba(0,0,0,0.3)" },
  cardTitle: { fontWeight: 800, fontSize: 14, marginBottom: 9, display: "flex", alignItems: "center", textTransform: "uppercase", letterSpacing: 1 },
  resRow: { display: "flex", flexWrap: "wrap", gap: 7 },
  resChip: { color: "#fff", borderRadius: 8, padding: "7px 9px", fontSize: 12, display: "flex", flexDirection: "column", alignItems: "center", minWidth: 58, border: "none", fontFamily: "inherit", boxShadow: "0 2px 5px rgba(0,0,0,0.3)" },
  devRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 8 },
  devChip: { background: PARCHMENT_DARK, borderRadius: 6, padding: "5px 9px", fontSize: 12, display: "flex", alignItems: "center", gap: 6 },
  miniBtn: { border: "none", background: SEA, color: PARCHMENT, borderRadius: 4, padding: "4px 8px", fontSize: 11, cursor: "pointer", minHeight: 26 },
  actionGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 7, marginBottom: 9 },
  toggleBtn: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", padding: "10px 6px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: "transparent", color: SEA, fontSize: 12.5, fontWeight: 700, cursor: "pointer", minHeight: 40 },
  toggleBtnActive: { display: "flex", alignItems: "center", gap: 6, justifyContent: "center", padding: "10px 6px", borderRadius: 6, border: `1.5px solid ${SEA}`, background: SEA, color: PARCHMENT, fontSize: 12.5, fontWeight: 700, cursor: "pointer", minHeight: 40 },
  hint: { fontSize: 13, color: "#5a4a35", marginBottom: 6 },
  playerCard: { display: "flex", alignItems: "center", gap: 9, padding: "8px 6px", borderLeft: "4px solid", marginBottom: 5, borderRadius: 4 },
  playerDot: { width: 11, height: 11, borderRadius: "50%", flexShrink: 0 },
  playerCardBody: { flex: 1, minWidth: 0 },
  playerCardName: { fontWeight: 700, fontSize: 14 },
  playerCardMeta: { fontSize: 11.5, color: "#5a4a35" },
  discardRow: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13, marginBottom: 5 },
  stepper: { display: "flex", alignItems: "center", gap: 8 },
  tradeRow: { display: "flex", gap: 8, marginBottom: 9 },
  select: { width: "100%", padding: 9, borderRadius: 6, border: `1.5px solid ${GOLD}`, background: "#fbf6e8", fontSize: 13, minHeight: 40 },
  logBox: { maxHeight: 160, overflowY: "auto", fontSize: 12.5, lineHeight: 1.6 },
  logLine: { borderBottom: "1px solid rgba(0,0,0,0.08)", padding: "4px 0" },
};
